<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="player.png" />
    <Resource Include="grass.png" />
    <Resource Include="forest.png" />
    <Resource Include="wood_set.png" />
    <Resource Include="stone_set.png" />
    <Resource Include="stone.png" />
    <Resource Include="water.png" />
  </ItemGroup>

</Project>
